/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedModelsRouteImport } from './routes/_authed/models'
import { Route as AuthedIntegrationsRouteImport } from './routes/_authed/integrations'
import { Route as AuthedHistoryRouteImport } from './routes/_authed/history'
import { Route as AuthedExtractionRouteImport } from './routes/_authed/extraction'
import { Route as AuthedModelsIndexRouteImport } from './routes/_authed/models/index'
import { Route as AuthedIntegrationsIndexRouteImport } from './routes/_authed/integrations/index'
import { Route as AuthedHistoryIndexRouteImport } from './routes/_authed/history/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AuthedModelsNewRouteImport } from './routes/_authed/models/new'
import { Route as AuthedModelsModelIdRouteImport } from './routes/_authed/models/$modelId'
import { Route as AuthedIntegrationsNewRouteImport } from './routes/_authed/integrations/new'
import { Route as AuthedHistoryExtractionIdRouteImport } from './routes/_authed/history/$extractionId'
import { Route as AuthedModelsModelIdIndexRouteImport } from './routes/_authed/models/$modelId/index'
import { Route as AuthedModelsModelIdEditRouteImport } from './routes/_authed/models/$modelId/edit'
import { Route as AuthedModelsModelIdVersionsNewRouteImport } from './routes/_authed/models/$modelId/versions/new'
import { Route as AuthedModelsModelIdVersionsVersionIdRouteImport } from './routes/_authed/models/$modelId/versions/$versionId'

const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedModelsRoute = AuthedModelsRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedIntegrationsRoute = AuthedIntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedHistoryRoute = AuthedHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedExtractionRoute = AuthedExtractionRouteImport.update({
  id: '/extraction',
  path: '/extraction',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedModelsIndexRoute = AuthedModelsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedModelsRoute,
} as any)
const AuthedIntegrationsIndexRoute = AuthedIntegrationsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedIntegrationsRoute,
} as any)
const AuthedHistoryIndexRoute = AuthedHistoryIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedHistoryRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedModelsNewRoute = AuthedModelsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthedModelsRoute,
} as any)
const AuthedModelsModelIdRoute = AuthedModelsModelIdRouteImport.update({
  id: '/$modelId',
  path: '/$modelId',
  getParentRoute: () => AuthedModelsRoute,
} as any)
const AuthedIntegrationsNewRoute = AuthedIntegrationsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthedIntegrationsRoute,
} as any)
const AuthedHistoryExtractionIdRoute =
  AuthedHistoryExtractionIdRouteImport.update({
    id: '/$extractionId',
    path: '/$extractionId',
    getParentRoute: () => AuthedHistoryRoute,
  } as any)
const AuthedModelsModelIdIndexRoute =
  AuthedModelsModelIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthedModelsModelIdRoute,
  } as any)
const AuthedModelsModelIdEditRoute = AuthedModelsModelIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => AuthedModelsModelIdRoute,
} as any)
const AuthedModelsModelIdVersionsNewRoute =
  AuthedModelsModelIdVersionsNewRouteImport.update({
    id: '/versions/new',
    path: '/versions/new',
    getParentRoute: () => AuthedModelsModelIdRoute,
  } as any)
const AuthedModelsModelIdVersionsVersionIdRoute =
  AuthedModelsModelIdVersionsVersionIdRouteImport.update({
    id: '/versions/$versionId',
    path: '/versions/$versionId',
    getParentRoute: () => AuthedModelsModelIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/extraction': typeof AuthedExtractionRoute
  '/history': typeof AuthedHistoryRouteWithChildren
  '/integrations': typeof AuthedIntegrationsRouteWithChildren
  '/models': typeof AuthedModelsRouteWithChildren
  '/history/$extractionId': typeof AuthedHistoryExtractionIdRoute
  '/integrations/new': typeof AuthedIntegrationsNewRoute
  '/models/$modelId': typeof AuthedModelsModelIdRouteWithChildren
  '/models/new': typeof AuthedModelsNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/history/': typeof AuthedHistoryIndexRoute
  '/integrations/': typeof AuthedIntegrationsIndexRoute
  '/models/': typeof AuthedModelsIndexRoute
  '/models/$modelId/edit': typeof AuthedModelsModelIdEditRoute
  '/models/$modelId/': typeof AuthedModelsModelIdIndexRoute
  '/models/$modelId/versions/$versionId': typeof AuthedModelsModelIdVersionsVersionIdRoute
  '/models/$modelId/versions/new': typeof AuthedModelsModelIdVersionsNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/extraction': typeof AuthedExtractionRoute
  '/history/$extractionId': typeof AuthedHistoryExtractionIdRoute
  '/integrations/new': typeof AuthedIntegrationsNewRoute
  '/models/new': typeof AuthedModelsNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/history': typeof AuthedHistoryIndexRoute
  '/integrations': typeof AuthedIntegrationsIndexRoute
  '/models': typeof AuthedModelsIndexRoute
  '/models/$modelId/edit': typeof AuthedModelsModelIdEditRoute
  '/models/$modelId': typeof AuthedModelsModelIdIndexRoute
  '/models/$modelId/versions/$versionId': typeof AuthedModelsModelIdVersionsVersionIdRoute
  '/models/$modelId/versions/new': typeof AuthedModelsModelIdVersionsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/_authed/extraction': typeof AuthedExtractionRoute
  '/_authed/history': typeof AuthedHistoryRouteWithChildren
  '/_authed/integrations': typeof AuthedIntegrationsRouteWithChildren
  '/_authed/models': typeof AuthedModelsRouteWithChildren
  '/_authed/history/$extractionId': typeof AuthedHistoryExtractionIdRoute
  '/_authed/integrations/new': typeof AuthedIntegrationsNewRoute
  '/_authed/models/$modelId': typeof AuthedModelsModelIdRouteWithChildren
  '/_authed/models/new': typeof AuthedModelsNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_authed/history/': typeof AuthedHistoryIndexRoute
  '/_authed/integrations/': typeof AuthedIntegrationsIndexRoute
  '/_authed/models/': typeof AuthedModelsIndexRoute
  '/_authed/models/$modelId/edit': typeof AuthedModelsModelIdEditRoute
  '/_authed/models/$modelId/': typeof AuthedModelsModelIdIndexRoute
  '/_authed/models/$modelId/versions/$versionId': typeof AuthedModelsModelIdVersionsVersionIdRoute
  '/_authed/models/$modelId/versions/new': typeof AuthedModelsModelIdVersionsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/extraction'
    | '/history'
    | '/integrations'
    | '/models'
    | '/history/$extractionId'
    | '/integrations/new'
    | '/models/$modelId'
    | '/models/new'
    | '/api/auth/$'
    | '/history/'
    | '/integrations/'
    | '/models/'
    | '/models/$modelId/edit'
    | '/models/$modelId/'
    | '/models/$modelId/versions/$versionId'
    | '/models/$modelId/versions/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/extraction'
    | '/history/$extractionId'
    | '/integrations/new'
    | '/models/new'
    | '/api/auth/$'
    | '/history'
    | '/integrations'
    | '/models'
    | '/models/$modelId/edit'
    | '/models/$modelId'
    | '/models/$modelId/versions/$versionId'
    | '/models/$modelId/versions/new'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/_authed/extraction'
    | '/_authed/history'
    | '/_authed/integrations'
    | '/_authed/models'
    | '/_authed/history/$extractionId'
    | '/_authed/integrations/new'
    | '/_authed/models/$modelId'
    | '/_authed/models/new'
    | '/api/auth/$'
    | '/_authed/history/'
    | '/_authed/integrations/'
    | '/_authed/models/'
    | '/_authed/models/$modelId/edit'
    | '/_authed/models/$modelId/'
    | '/_authed/models/$modelId/versions/$versionId'
    | '/_authed/models/$modelId/versions/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/models': {
      id: '/_authed/models'
      path: '/models'
      fullPath: '/models'
      preLoaderRoute: typeof AuthedModelsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/integrations': {
      id: '/_authed/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof AuthedIntegrationsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/history': {
      id: '/_authed/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AuthedHistoryRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/extraction': {
      id: '/_authed/extraction'
      path: '/extraction'
      fullPath: '/extraction'
      preLoaderRoute: typeof AuthedExtractionRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/models/': {
      id: '/_authed/models/'
      path: '/'
      fullPath: '/models/'
      preLoaderRoute: typeof AuthedModelsIndexRouteImport
      parentRoute: typeof AuthedModelsRoute
    }
    '/_authed/integrations/': {
      id: '/_authed/integrations/'
      path: '/'
      fullPath: '/integrations/'
      preLoaderRoute: typeof AuthedIntegrationsIndexRouteImport
      parentRoute: typeof AuthedIntegrationsRoute
    }
    '/_authed/history/': {
      id: '/_authed/history/'
      path: '/'
      fullPath: '/history/'
      preLoaderRoute: typeof AuthedHistoryIndexRouteImport
      parentRoute: typeof AuthedHistoryRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/models/new': {
      id: '/_authed/models/new'
      path: '/new'
      fullPath: '/models/new'
      preLoaderRoute: typeof AuthedModelsNewRouteImport
      parentRoute: typeof AuthedModelsRoute
    }
    '/_authed/models/$modelId': {
      id: '/_authed/models/$modelId'
      path: '/$modelId'
      fullPath: '/models/$modelId'
      preLoaderRoute: typeof AuthedModelsModelIdRouteImport
      parentRoute: typeof AuthedModelsRoute
    }
    '/_authed/integrations/new': {
      id: '/_authed/integrations/new'
      path: '/new'
      fullPath: '/integrations/new'
      preLoaderRoute: typeof AuthedIntegrationsNewRouteImport
      parentRoute: typeof AuthedIntegrationsRoute
    }
    '/_authed/history/$extractionId': {
      id: '/_authed/history/$extractionId'
      path: '/$extractionId'
      fullPath: '/history/$extractionId'
      preLoaderRoute: typeof AuthedHistoryExtractionIdRouteImport
      parentRoute: typeof AuthedHistoryRoute
    }
    '/_authed/models/$modelId/': {
      id: '/_authed/models/$modelId/'
      path: '/'
      fullPath: '/models/$modelId/'
      preLoaderRoute: typeof AuthedModelsModelIdIndexRouteImport
      parentRoute: typeof AuthedModelsModelIdRoute
    }
    '/_authed/models/$modelId/edit': {
      id: '/_authed/models/$modelId/edit'
      path: '/edit'
      fullPath: '/models/$modelId/edit'
      preLoaderRoute: typeof AuthedModelsModelIdEditRouteImport
      parentRoute: typeof AuthedModelsModelIdRoute
    }
    '/_authed/models/$modelId/versions/new': {
      id: '/_authed/models/$modelId/versions/new'
      path: '/versions/new'
      fullPath: '/models/$modelId/versions/new'
      preLoaderRoute: typeof AuthedModelsModelIdVersionsNewRouteImport
      parentRoute: typeof AuthedModelsModelIdRoute
    }
    '/_authed/models/$modelId/versions/$versionId': {
      id: '/_authed/models/$modelId/versions/$versionId'
      path: '/versions/$versionId'
      fullPath: '/models/$modelId/versions/$versionId'
      preLoaderRoute: typeof AuthedModelsModelIdVersionsVersionIdRouteImport
      parentRoute: typeof AuthedModelsModelIdRoute
    }
  }
}

interface AuthedHistoryRouteChildren {
  AuthedHistoryExtractionIdRoute: typeof AuthedHistoryExtractionIdRoute
  AuthedHistoryIndexRoute: typeof AuthedHistoryIndexRoute
}

const AuthedHistoryRouteChildren: AuthedHistoryRouteChildren = {
  AuthedHistoryExtractionIdRoute: AuthedHistoryExtractionIdRoute,
  AuthedHistoryIndexRoute: AuthedHistoryIndexRoute,
}

const AuthedHistoryRouteWithChildren = AuthedHistoryRoute._addFileChildren(
  AuthedHistoryRouteChildren,
)

interface AuthedIntegrationsRouteChildren {
  AuthedIntegrationsNewRoute: typeof AuthedIntegrationsNewRoute
  AuthedIntegrationsIndexRoute: typeof AuthedIntegrationsIndexRoute
}

const AuthedIntegrationsRouteChildren: AuthedIntegrationsRouteChildren = {
  AuthedIntegrationsNewRoute: AuthedIntegrationsNewRoute,
  AuthedIntegrationsIndexRoute: AuthedIntegrationsIndexRoute,
}

const AuthedIntegrationsRouteWithChildren =
  AuthedIntegrationsRoute._addFileChildren(AuthedIntegrationsRouteChildren)

interface AuthedModelsModelIdRouteChildren {
  AuthedModelsModelIdEditRoute: typeof AuthedModelsModelIdEditRoute
  AuthedModelsModelIdIndexRoute: typeof AuthedModelsModelIdIndexRoute
  AuthedModelsModelIdVersionsVersionIdRoute: typeof AuthedModelsModelIdVersionsVersionIdRoute
  AuthedModelsModelIdVersionsNewRoute: typeof AuthedModelsModelIdVersionsNewRoute
}

const AuthedModelsModelIdRouteChildren: AuthedModelsModelIdRouteChildren = {
  AuthedModelsModelIdEditRoute: AuthedModelsModelIdEditRoute,
  AuthedModelsModelIdIndexRoute: AuthedModelsModelIdIndexRoute,
  AuthedModelsModelIdVersionsVersionIdRoute:
    AuthedModelsModelIdVersionsVersionIdRoute,
  AuthedModelsModelIdVersionsNewRoute: AuthedModelsModelIdVersionsNewRoute,
}

const AuthedModelsModelIdRouteWithChildren =
  AuthedModelsModelIdRoute._addFileChildren(AuthedModelsModelIdRouteChildren)

interface AuthedModelsRouteChildren {
  AuthedModelsModelIdRoute: typeof AuthedModelsModelIdRouteWithChildren
  AuthedModelsNewRoute: typeof AuthedModelsNewRoute
  AuthedModelsIndexRoute: typeof AuthedModelsIndexRoute
}

const AuthedModelsRouteChildren: AuthedModelsRouteChildren = {
  AuthedModelsModelIdRoute: AuthedModelsModelIdRouteWithChildren,
  AuthedModelsNewRoute: AuthedModelsNewRoute,
  AuthedModelsIndexRoute: AuthedModelsIndexRoute,
}

const AuthedModelsRouteWithChildren = AuthedModelsRoute._addFileChildren(
  AuthedModelsRouteChildren,
)

interface AuthedRouteChildren {
  AuthedExtractionRoute: typeof AuthedExtractionRoute
  AuthedHistoryRoute: typeof AuthedHistoryRouteWithChildren
  AuthedIntegrationsRoute: typeof AuthedIntegrationsRouteWithChildren
  AuthedModelsRoute: typeof AuthedModelsRouteWithChildren
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedExtractionRoute: AuthedExtractionRoute,
  AuthedHistoryRoute: AuthedHistoryRouteWithChildren,
  AuthedIntegrationsRoute: AuthedIntegrationsRouteWithChildren,
  AuthedModelsRoute: AuthedModelsRouteWithChildren,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
